description: "This research project develops training materials for reseachers wanting to learn to build project
websites in GitHub with GitHub Pages."
email: "<team@carpentries.org>"
email2: "team@carpentries.org"

students: 
  - name: "Evan Connors"
    project: "SERS substrate LB fabricaation"
    degree: "PhD"
  - name : "Parisa"
    project: "eye tissue"
    degree: "BSc"
  - name : "Lauren Ead"
    project: "TERS and microplastics"
    degree: "PhD"
    program: "Env Sci"
